### ISSUE TITLE
Modify argv handling

### ISSUE THREAD

**Issue by MakisH** [MakisH/CFDLab#17]
Modify the main to take a "problem" argument, read the corresponding configuration file under configs/ and write the vtk files under results/problem/.

**Comment by martosss** [comment]
In the problem.dat file we should have
- scenario name saved in char *problem (const?);
- additional scenario parameters as stated on page 13 (x-,y-,z-length, tau, t, ro_in and ro_ref or v_in)
- anything else? :thought_balloon:

**Comment by martosss** [comment]
I just had a look in the config files ... There are parameters wall 1, 2, 3, 4, 5, 6, but the scenarios are fixed ... so we  can either hard code each scenario or pass wall1-6 as parameters to initialiseFields() and make it flexible there(should be easy, although the scenarios are pretty fixed and we can't do anything else than them).

Another thing - there are all parameters in each file ... it seems too much - we could include only the necessary ones for the particular scenario and if-else our way through them... although that will actually make the code a bit worse .. but we wouldn't process "dead" data.

**Comment by martosss** [comment]
Reading is done ...

Now we need the visualvtk ...

Shouldn't it be similar to the previous scenario ? Probably the arbitrary geometries will be a bit strange, because we'll show also inner boundary cells, but who cares? :thought_balloon:  Otherwise we should ... change the type of geometry to sparse vtk file and include only boundaries ... more work :disappointed:

**Comment by martosss** [comment]
visualVTK is also be working now.
