### ISSUE TITLE
Check treatBoundary() limits

### ISSUE THREAD

**Issue by MakisH** [MakisH/CFDLab#5]
During debugging, I thought the solution to a bug was to not touch the same boundary point again. Maybe this was not implemented correctly. Check!

**Comment by martosss** [comment]
1) I agree - we should update collideField only once in each boundary cell in each relevant direction(~5 directions/boundary cell, less around the edges/corners)

2) In our code I think that eachSize(1-5) should depend NOT on the boundary value(1-6), but on how close the respective cell is to the edges/corners(going from 5 for "inner" boundary cells to 1 for cells on the edge(it could be 1 3 4 5(0 for the boundary corners, which don't play any role))
here is how I imagine the influence of the boundary for a 4x4x4 FLUID cell domain. The numbers indicate how many FLUID cells are affected by the respective boundary cell
`011110`
`134431`
`145541`
`145541`
`134431`
`011110`

3) Having said 2), I think that a better solution is to loop over all directions, because each direction participates 16 times(4²) for each boundary wall in the example above( :shit: edges are more tricky, because they participate in two boundaries and will be counted twice). We probably will need 1 loop for each case(and for each boundary/corner?).

**Comment by MakisH** [comment]
It looks ok in my last commit, we checked it with martosss.
