### ISSUE TITLE
Saving VTK files

### ISSUE THREAD

**Issue by martosss** [MakisH/CFDLab#9]
Yesterday I played with the visualization of our solution and after being finished, I saved my data (vtk files + stream filter + glyph filter) ... after that came the surprise when I tried to actually open it again and use it - Paraview didn't know which reader to use to identify my data ... so do you have an idea if it is possible to save it in a proper way and which reader we should rely on?(there was some kind of VTK reader, but it produced an error when picked... it gave me to choose from nearly 30 different file readers - I am not the author of Paraview to know them all :-( )

**Comment by MakisH** [comment]
As you found out, you can use any text editor to open the (ASCII) vtk files.

**Comment by martosss** [comment]
It's not about the vtk files - I want to save my current configuration in paraview, for example I have loaded some particular file, then created a glyph and a stream tracer and I want to save this configuration, so that the next time I open it, I have already everything loaded and set up - I don't want to do the whole loading process for every file I load.

**Comment by MakisH** [comment]
I tried to do the same. I loaded a file, I added some streamlines and I pressed "Save state". It saved an xml-like ".pvsm" file with just the configuration (not the data). I saved it in a different directory than the data vtk file.

When I tried to load it, it had already chosen a "legacy reader" and it just asked for the data file.
I suppose they just don't provide the option to save the data with the configuration, because the data files can be really huge (and they are in a different format). They could create a new packet-like file format, but I suppose they just haven't done it.

More: http://www.paraview.org/Wiki/Advanced_State_Management

I think this is the only but a sufficient way to deal with saving the configuration, so I close the issue. :-)
